# Generated by Django 3.0 on 2019-12-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('img', models.CharField(max_length=40)),
            ],
        ),
    ]
